git  submodule  add https://github.com/Townk/vim-autoclose.git bundle/autoclose
git  submodule  add https://github.com/tpope/vim-surround.git bundle/surround
git  submodule  add https://github.com/Twinside/vim-cuteErrorMarker.git bundle/CuteErrorMarker
git  submodule  add https://github.com/vim-scripts/YankRing.vim.git bundle/yankring
git  submodule  add https://github.com/vim-scripts/VisIncr.git bundle/VisIncr
git  submodule  add https://github.com/sukima/xmledit.git bundle/xmledit
git  submodule  add https://github.com/vim-scripts/matchit.zip.git bundle/matchit
git  submodule  add https://github.com/vim-scripts/javacomplete bundle/javacomplete
git  submodule  add https://github.com/scrooloose/nerdtree.git bundle/nerdtree
git  submodule  add https://github.com/scrooloose/nerdcommenter.git bundle/nerdcommenter
git  submodule  add git://github.com/Lokaltog/vim-easymotion.git bundle/easymotion
git  submodule  add git://github.com/majutsushi/tagbar bundle/tagbar
git  submodule  add https://github.com/vim-scripts/pythoncomplete.git bundle/pythoncomplete
git  submodule  add https://github.com/Lokaltog/vim-powerline.git bundle/powerline
git  submodule  add https://github.com/pangloss/vim-javascript.git bundle/vim-javascript
git  submodule  add https://github.com/vim-scripts/pythoncomplete.git bundle/pythoncomplete
git  submodule  add https://github.com/Lokaltog/vim-powerline.git bundle/powerline
git  submodule  add https://github.com/pangloss/vim-javascript.git bundle/vim-javascript
git  submodule  add https://github.com/MarcWeber/vim-addon-mw-utils.git bundle/vim-addon-mw-utils
git  submodule  add https://github.com/mattn/emmet-vim.git bundle/emmet-vim
git  submodule  add git://github.com/mileszs/ack.vim.git bundle/ack.vim
git  submodule  add git://github.com/MiCHiLU/pyflakes-vim.git bundle/pyflakes-vim
git  submodule  add git://github.com/kchmck/vim-coffee-script.git bundle/vim-coffee-script
git  submodule  add git://github.com/airblade/vim-gitgutter.git bundle/vim-gitgutter
git  submodule  add https://github.com/Valloric/YouCompleteMe.git bundle/YouCompleteMe
git  submodule  add https://github.com/SirVer/ultisnips.git bundle/ultisnips
git  submodule  add https://github.com/kien/ctrlp.vim.git bundle/ctrlp
git  submodule  add https://github.com/nathanaelkane/vim-indent-guides.git bundle/vim-indent-guides
git  submodule  add https://github.com/godlygeek/tabular.git bundle/tabular
git  submodule  add https://github.com/kana/vim-operator-user.git bundle/vim-operator-user
git submodule add https://github.com/rhysd/vim-clang-format.git bundle/vim-clang-format
git submodule add git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex/ bundle/vim-latex
git submodule add git://github.com/vim-scripts/indent-motion.git bundle/indent-motion
git submodule add https://github.com/tpope/vim-fugitive.git bundle/fugitive
